#!/usr/bin/env bash
set -euo pipefail

GREEN="$(printf '\033[1;32m')"
YELLOW="$(printf '\033[1;33m')"
RED="$(printf '\033[1;31m')"
NC="$(printf '\033[0m')"

SYSTEM_TYPE="aarch64-darwin"
FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

export NIXPKGS_ALLOW_UNFREE=1
nix_args=(--extra-experimental-features 'nix-command flakes')

echo "${YELLOW}Starting build...${NC}"
nix "${nix_args[@]}" build ".#${FLAKE_SYSTEM}" "$@"

echo "${YELLOW}Storing result in remote cache...${NC}"
nix "${nix_args[@]}" store sign --recursive -k /etc/nix/secret-key "$(readlink ./result)"
nix "${nix_args[@]}" copy --to "s3://io-vandaele-nix-cache?endpoint=https://storage.googleapis.com&profile=gcp" "$(readlink result)"

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Build with copy to cache complete!${NC}"
