name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.24.11/install
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build darwin configuration
        run: |
          nix build '.#darwinConfigurations.aarch64-darwin.system' \
            --override-input secrets 'path:./ci/secrets-stub' \
            --dry-run
